services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'adminSenha'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'adminSenha'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - /Users/joaopedroldavid/Diretório - VSCode/RocketSeat/Python/Flask_SQLAlchemy/MySQL:/var/lib/mysql